/* This file is auto-generated from "geldkarte_values.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef GELDKARTE_VALUES_L_H
#define GELDKARTE_VALUES_L_H

/** @page P_LC_GELDKARTE_VALUES_LIB LC_GeldKarte_Values (lib)
This page describes the properties of LC_GELDKARTE_VALUES
*/
#include "geldkarte_values.h"

#ifdef __cplusplus
extern "C" {
#endif







#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* GELDKARTE_VALUES_L_H */
