/* This file is auto-generated from "geldkarte_blog.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef GELDKARTE_BLOG_P_H
#define GELDKARTE_BLOG_P_H

#include "geldkarte_blog_l.h"


struct LC_GELDKARTE_BLOG {
  int _usage;
  int _modified;

  int status;
  int bSeq;
  int lSeq;
  int value;
  char *merchantId;
  int hSeq;
  int sSeq;
  int loaded;
  GWEN_TIME *time;
  int keyId;
};













#endif /* GELDKARTE_BLOG_P_H */
