/* This file is auto-generated from "geldkarte_blog.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "geldkarte_blog_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>
#include <strings.h>

#include <gwenhywfar/types.h>
#include <gwenhywfar/gwentime.h>
#include <chipcard/chipcard.h>


GWEN_LIST2_FUNCTIONS(LC_GELDKARTE_BLOG, LC_GeldKarte_BLog)




LC_GELDKARTE_BLOG *LC_GeldKarte_BLog_new() {
  LC_GELDKARTE_BLOG *st;

  GWEN_NEW_OBJECT(LC_GELDKARTE_BLOG, st)
  st->_usage=1;
  return st;
}


void LC_GeldKarte_BLog_free(LC_GELDKARTE_BLOG *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  if (st->merchantId)
    free(st->merchantId);
  if (st->time)
    GWEN_Time_free(st->time);
  GWEN_FREE_OBJECT(st);
    }
  }

}


LC_GELDKARTE_BLOG *LC_GeldKarte_BLog_dup(const LC_GELDKARTE_BLOG *d) {
  LC_GELDKARTE_BLOG *st;

  assert(d);
  st=LC_GeldKarte_BLog_new();
  st->status=d->status;
  st->bSeq=d->bSeq;
  st->lSeq=d->lSeq;
  st->value=d->value;
  if (d->merchantId)
    st->merchantId=strdup(d->merchantId);
  st->hSeq=d->hSeq;
  st->sSeq=d->sSeq;
  st->loaded=d->loaded;
  if (d->time)
    st->time=GWEN_Time_dup(d->time);
  st->keyId=d->keyId;
  return st;
}


int LC_GeldKarte_BLog_toDb(const LC_GELDKARTE_BLOG *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "status", st->status))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "bSeq", st->bSeq))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "lSeq", st->lSeq))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "value", st->value))
    return -1;
  if (st->merchantId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "merchantId", st->merchantId))
      return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "hSeq", st->hSeq))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "sSeq", st->sSeq))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "loaded", st->loaded))
    return -1;
  if (st->time)
    if (GWEN_Time_toDb(st->time, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "time")))
      return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "keyId", st->keyId))
    return -1;
  return 0;
}


int LC_GeldKarte_BLog_ReadDb(LC_GELDKARTE_BLOG *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  LC_GeldKarte_BLog_SetStatus(st, GWEN_DB_GetIntValue(db, "status", 0, 0));
  LC_GeldKarte_BLog_SetBSeq(st, GWEN_DB_GetIntValue(db, "bSeq", 0, 0));
  LC_GeldKarte_BLog_SetLSeq(st, GWEN_DB_GetIntValue(db, "lSeq", 0, 0));
  LC_GeldKarte_BLog_SetValue(st, GWEN_DB_GetIntValue(db, "value", 0, 0));
  LC_GeldKarte_BLog_SetMerchantId(st, GWEN_DB_GetCharValue(db, "merchantId", 0, 0));
  LC_GeldKarte_BLog_SetHSeq(st, GWEN_DB_GetIntValue(db, "hSeq", 0, 0));
  LC_GeldKarte_BLog_SetSSeq(st, GWEN_DB_GetIntValue(db, "sSeq", 0, 0));
  LC_GeldKarte_BLog_SetLoaded(st, GWEN_DB_GetIntValue(db, "loaded", 0, 0));
  if (1) { /* for local vars */
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "time");
    if (dbT) {
  if (st->time)
    GWEN_Time_free(st->time);
  st->time=GWEN_Time_fromDb(dbT);
}
  }
  LC_GeldKarte_BLog_SetKeyId(st, GWEN_DB_GetIntValue(db, "keyId", 0, 0));
  return 0;
}


LC_GELDKARTE_BLOG *LC_GeldKarte_BLog_fromDb(GWEN_DB_NODE *db) {
  LC_GELDKARTE_BLOG *st;

  assert(db);
  st=LC_GeldKarte_BLog_new();
  LC_GeldKarte_BLog_ReadDb(st, db);
  st->_modified=0;
  return st;
}




int LC_GeldKarte_BLog_GetStatus(const LC_GELDKARTE_BLOG *st) {
  assert(st);
  return st->status;
}


void LC_GeldKarte_BLog_SetStatus(LC_GELDKARTE_BLOG *st, int d) {
  assert(st);
  st->status=d;
  st->_modified=1;
}




int LC_GeldKarte_BLog_GetBSeq(const LC_GELDKARTE_BLOG *st) {
  assert(st);
  return st->bSeq;
}


void LC_GeldKarte_BLog_SetBSeq(LC_GELDKARTE_BLOG *st, int d) {
  assert(st);
  st->bSeq=d;
  st->_modified=1;
}




int LC_GeldKarte_BLog_GetLSeq(const LC_GELDKARTE_BLOG *st) {
  assert(st);
  return st->lSeq;
}


void LC_GeldKarte_BLog_SetLSeq(LC_GELDKARTE_BLOG *st, int d) {
  assert(st);
  st->lSeq=d;
  st->_modified=1;
}




int LC_GeldKarte_BLog_GetValue(const LC_GELDKARTE_BLOG *st) {
  assert(st);
  return st->value;
}


void LC_GeldKarte_BLog_SetValue(LC_GELDKARTE_BLOG *st, int d) {
  assert(st);
  st->value=d;
  st->_modified=1;
}




const char *LC_GeldKarte_BLog_GetMerchantId(const LC_GELDKARTE_BLOG *st) {
  assert(st);
  return st->merchantId;
}


void LC_GeldKarte_BLog_SetMerchantId(LC_GELDKARTE_BLOG *st, const char *d) {
  assert(st);
  if (st->merchantId)
    free(st->merchantId);
  if (d && *d)
    st->merchantId=strdup(d);
  else
    st->merchantId=0;
  st->_modified=1;
}




int LC_GeldKarte_BLog_GetHSeq(const LC_GELDKARTE_BLOG *st) {
  assert(st);
  return st->hSeq;
}


void LC_GeldKarte_BLog_SetHSeq(LC_GELDKARTE_BLOG *st, int d) {
  assert(st);
  st->hSeq=d;
  st->_modified=1;
}




int LC_GeldKarte_BLog_GetSSeq(const LC_GELDKARTE_BLOG *st) {
  assert(st);
  return st->sSeq;
}


void LC_GeldKarte_BLog_SetSSeq(LC_GELDKARTE_BLOG *st, int d) {
  assert(st);
  st->sSeq=d;
  st->_modified=1;
}




int LC_GeldKarte_BLog_GetLoaded(const LC_GELDKARTE_BLOG *st) {
  assert(st);
  return st->loaded;
}


void LC_GeldKarte_BLog_SetLoaded(LC_GELDKARTE_BLOG *st, int d) {
  assert(st);
  st->loaded=d;
  st->_modified=1;
}




const GWEN_TIME *LC_GeldKarte_BLog_GetTime(const LC_GELDKARTE_BLOG *st) {
  assert(st);
  return st->time;
}


void LC_GeldKarte_BLog_SetTime(LC_GELDKARTE_BLOG *st, const GWEN_TIME *d) {
  assert(st);
  if (st->time)
    GWEN_Time_free(st->time);
  if (d)
    st->time=GWEN_Time_dup(d);
  else
    st->time=0;
  st->_modified=1;
}




int LC_GeldKarte_BLog_GetKeyId(const LC_GELDKARTE_BLOG *st) {
  assert(st);
  return st->keyId;
}


void LC_GeldKarte_BLog_SetKeyId(LC_GELDKARTE_BLOG *st, int d) {
  assert(st);
  st->keyId=d;
  st->_modified=1;
}




int LC_GeldKarte_BLog_IsModified(const LC_GELDKARTE_BLOG *st) {
  assert(st);
  return st->_modified;
}


void LC_GeldKarte_BLog_SetModified(LC_GELDKARTE_BLOG *st, int i) {
  assert(st);
  st->_modified=i;
}


void LC_GeldKarte_BLog_Attach(LC_GELDKARTE_BLOG *st) {
  assert(st);
  st->_usage++;
}
LC_GELDKARTE_BLOG *LC_GeldKarte_BLog_List2__freeAll_cb(LC_GELDKARTE_BLOG *st, void *user_data) {
  LC_GeldKarte_BLog_free(st);
return 0;
}


void LC_GeldKarte_BLog_List2_freeAll(LC_GELDKARTE_BLOG_LIST2 *stl) {
  if (stl) {
    LC_GeldKarte_BLog_List2_ForEach(stl, LC_GeldKarte_BLog_List2__freeAll_cb, 0);
    LC_GeldKarte_BLog_List2_free(stl); 
  }
}




