/* This file is auto-generated from "geldkarte_llog.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef GELDKARTE_LLOG_P_H
#define GELDKARTE_LLOG_P_H

#include "geldkarte_llog_l.h"


struct LC_GELDKARTE_LLOG {
  int _usage;
  int _modified;

  int status;
  int bSeq;
  int lSeq;
  int value;
  char *centerId;
  char *terminalId;
  char *traceId;
  int loaded;
  GWEN_TIME *time;
};












#endif /* GELDKARTE_LLOG_P_H */
