/* This file is auto-generated from "geldkarte_values.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef GELDKARTE_VALUES_P_H
#define GELDKARTE_VALUES_P_H

#include "geldkarte_values_l.h"


struct LC_GELDKARTE_VALUES {
  int _usage;
  int _modified;

  int loaded;
  int maxLoad;
  int maxXfer;
};






#endif /* GELDKARTE_VALUES_P_H */
