/* This file is auto-generated from "geldkarte_values.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "geldkarte_values_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>
#include <strings.h>

#include <gwenhywfar/types.h>
#include <gwenhywfar/gwentime.h>
#include <chipcard/chipcard.h>


GWEN_LIST2_FUNCTIONS(LC_GELDKARTE_VALUES, LC_GeldKarte_Values)




LC_GELDKARTE_VALUES *LC_GeldKarte_Values_new() {
  LC_GELDKARTE_VALUES *st;

  GWEN_NEW_OBJECT(LC_GELDKARTE_VALUES, st)
  st->_usage=1;
  return st;
}


void LC_GeldKarte_Values_free(LC_GELDKARTE_VALUES *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  GWEN_FREE_OBJECT(st);
    }
  }

}


LC_GELDKARTE_VALUES *LC_GeldKarte_Values_dup(const LC_GELDKARTE_VALUES *d) {
  LC_GELDKARTE_VALUES *st;

  assert(d);
  st=LC_GeldKarte_Values_new();
  st->loaded=d->loaded;
  st->maxLoad=d->maxLoad;
  st->maxXfer=d->maxXfer;
  return st;
}


int LC_GeldKarte_Values_toDb(const LC_GELDKARTE_VALUES *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "loaded", st->loaded))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "maxLoad", st->maxLoad))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "maxXfer", st->maxXfer))
    return -1;
  return 0;
}


int LC_GeldKarte_Values_ReadDb(LC_GELDKARTE_VALUES *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  LC_GeldKarte_Values_SetLoaded(st, GWEN_DB_GetIntValue(db, "loaded", 0, 0));
  LC_GeldKarte_Values_SetMaxLoad(st, GWEN_DB_GetIntValue(db, "maxLoad", 0, 0));
  LC_GeldKarte_Values_SetMaxXfer(st, GWEN_DB_GetIntValue(db, "maxXfer", 0, 0));
  return 0;
}


LC_GELDKARTE_VALUES *LC_GeldKarte_Values_fromDb(GWEN_DB_NODE *db) {
  LC_GELDKARTE_VALUES *st;

  assert(db);
  st=LC_GeldKarte_Values_new();
  LC_GeldKarte_Values_ReadDb(st, db);
  st->_modified=0;
  return st;
}




int LC_GeldKarte_Values_GetLoaded(const LC_GELDKARTE_VALUES *st) {
  assert(st);
  return st->loaded;
}


void LC_GeldKarte_Values_SetLoaded(LC_GELDKARTE_VALUES *st, int d) {
  assert(st);
  st->loaded=d;
  st->_modified=1;
}




int LC_GeldKarte_Values_GetMaxLoad(const LC_GELDKARTE_VALUES *st) {
  assert(st);
  return st->maxLoad;
}


void LC_GeldKarte_Values_SetMaxLoad(LC_GELDKARTE_VALUES *st, int d) {
  assert(st);
  st->maxLoad=d;
  st->_modified=1;
}




int LC_GeldKarte_Values_GetMaxXfer(const LC_GELDKARTE_VALUES *st) {
  assert(st);
  return st->maxXfer;
}


void LC_GeldKarte_Values_SetMaxXfer(LC_GELDKARTE_VALUES *st, int d) {
  assert(st);
  st->maxXfer=d;
  st->_modified=1;
}




int LC_GeldKarte_Values_IsModified(const LC_GELDKARTE_VALUES *st) {
  assert(st);
  return st->_modified;
}


void LC_GeldKarte_Values_SetModified(LC_GELDKARTE_VALUES *st, int i) {
  assert(st);
  st->_modified=i;
}


void LC_GeldKarte_Values_Attach(LC_GELDKARTE_VALUES *st) {
  assert(st);
  st->_usage++;
}
LC_GELDKARTE_VALUES *LC_GeldKarte_Values_List2__freeAll_cb(LC_GELDKARTE_VALUES *st, void *user_data) {
  LC_GeldKarte_Values_free(st);
return 0;
}


void LC_GeldKarte_Values_List2_freeAll(LC_GELDKARTE_VALUES_LIST2 *stl) {
  if (stl) {
    LC_GeldKarte_Values_List2_ForEach(stl, LC_GeldKarte_Values_List2__freeAll_cb, 0);
    LC_GeldKarte_Values_List2_free(stl); 
  }
}




