/* This file is auto-generated from "geldkarte_blog.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef GELDKARTE_BLOG_L_H
#define GELDKARTE_BLOG_L_H

/** @page P_LC_GELDKARTE_BLOG_LIB LC_GeldKarte_BLog (lib)
This page describes the properties of LC_GELDKARTE_BLOG
*/
#include "geldkarte_blog.h"

#ifdef __cplusplus
extern "C" {
#endif














#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* GELDKARTE_BLOG_L_H */
