/* This file is auto-generated from "geldkarte_llog.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef GELDKARTE_LLOG_L_H
#define GELDKARTE_LLOG_L_H

/** @page P_LC_GELDKARTE_LLOG_LIB LC_GeldKarte_LLog (lib)
This page describes the properties of LC_GELDKARTE_LLOG
*/
#include "geldkarte_llog.h"

#ifdef __cplusplus
extern "C" {
#endif













#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* GELDKARTE_LLOG_L_H */
