/* This file is auto-generated from "hiinsurancedata.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef HIINSURANCEDATA_L_H
#define HIINSURANCEDATA_L_H

/** @page P_LC_HI_INSURANCE_DATA_LIB LC_HIInsuranceData (lib)
This page describes the properties of LC_HI_INSURANCE_DATA
*/
#include <gwenhywfar/misc.h>
#include <gwenhywfar/list2.h>
#include "hiinsurancedata.h"
#include <gwenhywfar/misc.h>

#ifdef __cplusplus
extern "C" {
#endif


GWEN_LIST_FUNCTION_DEFS(LC_HI_INSURANCE_DATA, LC_HIInsuranceData)
LC_HI_INSURANCE_DATA_LIST *LC_HIInsuranceData_List_dup(const LC_HI_INSURANCE_DATA_LIST *stl);

GWEN_LIST2_FUNCTION_DEFS(LC_HI_INSURANCE_DATA, LC_HIInsuranceData)

void LC_HIInsuranceData_List2_freeAll(LC_HI_INSURANCE_DATA_LIST2 *stl);









#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* HIINSURANCEDATA_L_H */
