/* This file is auto-generated from "hiinsurancedata.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "hiinsurancedata_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>
#include <strings.h>

#include <chipcard/chipcard.h>
#include <gwenhywfar/gwentime.h>


GWEN_LIST_FUNCTIONS(LC_HI_INSURANCE_DATA, LC_HIInsuranceData)
GWEN_LIST2_FUNCTIONS(LC_HI_INSURANCE_DATA, LC_HIInsuranceData)




LC_HI_INSURANCE_DATA *LC_HIInsuranceData_new() {
  LC_HI_INSURANCE_DATA *st;

  GWEN_NEW_OBJECT(LC_HI_INSURANCE_DATA, st)
  st->_usage=1;
  GWEN_LIST_INIT(LC_HI_INSURANCE_DATA, st)
  return st;
}


void LC_HIInsuranceData_free(LC_HI_INSURANCE_DATA *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  if (st->institutionId)
    free(st->institutionId);
  if (st->institutionName)
    free(st->institutionName);
  if (st->coverBegin)
    GWEN_Time_free(st->coverBegin);
  if (st->coverEnd)
    GWEN_Time_free(st->coverEnd);
  if (st->status)
    free(st->status);
  if (st->group)
    free(st->group);
  GWEN_LIST_FINI(LC_HI_INSURANCE_DATA, st)
  GWEN_FREE_OBJECT(st);
    }
  }

}


LC_HI_INSURANCE_DATA *LC_HIInsuranceData_dup(const LC_HI_INSURANCE_DATA *d) {
  LC_HI_INSURANCE_DATA *st;

  assert(d);
  st=LC_HIInsuranceData_new();
  if (d->institutionId)
    st->institutionId=strdup(d->institutionId);
  if (d->institutionName)
    st->institutionName=strdup(d->institutionName);
  if (d->coverBegin)
    st->coverBegin=GWEN_Time_dup(d->coverBegin);
  if (d->coverEnd)
    st->coverEnd=GWEN_Time_dup(d->coverEnd);
  if (d->status)
    st->status=strdup(d->status);
  if (d->group)
    st->group=strdup(d->group);
  return st;
}


int LC_HIInsuranceData_toDb(const LC_HI_INSURANCE_DATA *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (st->institutionId)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "institutionId", st->institutionId))
      return -1;
  if (st->institutionName)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "institutionName", st->institutionName))
      return -1;
  if (st->coverBegin)
    if (GWEN_Time_toDb(st->coverBegin, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "coverBegin")))
      return -1;
  if (st->coverEnd)
    if (GWEN_Time_toDb(st->coverEnd, GWEN_DB_GetGroup(db, GWEN_DB_FLAGS_DEFAULT, "coverEnd")))
      return -1;
  if (st->status)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "status", st->status))
      return -1;
  if (st->group)
    if (GWEN_DB_SetCharValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "group", st->group))
      return -1;
  return 0;
}


int LC_HIInsuranceData_ReadDb(LC_HI_INSURANCE_DATA *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  LC_HIInsuranceData_SetInstitutionId(st, GWEN_DB_GetCharValue(db, "institutionId", 0, 0));
  LC_HIInsuranceData_SetInstitutionName(st, GWEN_DB_GetCharValue(db, "institutionName", 0, 0));
  if (1) { /* for local vars */
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "coverBegin");
    if (dbT) {
  if (st->coverBegin)
    GWEN_Time_free(st->coverBegin);
  st->coverBegin=GWEN_Time_fromDb(dbT);
}
  }
  if (1) { /* for local vars */
    GWEN_DB_NODE *dbT;

    dbT=GWEN_DB_GetGroup(db, GWEN_PATH_FLAGS_NAMEMUSTEXIST, "coverEnd");
    if (dbT) {
  if (st->coverEnd)
    GWEN_Time_free(st->coverEnd);
  st->coverEnd=GWEN_Time_fromDb(dbT);
}
  }
  LC_HIInsuranceData_SetStatus(st, GWEN_DB_GetCharValue(db, "status", 0, 0));
  LC_HIInsuranceData_SetGroup(st, GWEN_DB_GetCharValue(db, "group", 0, 0));
  return 0;
}


LC_HI_INSURANCE_DATA *LC_HIInsuranceData_fromDb(GWEN_DB_NODE *db) {
  LC_HI_INSURANCE_DATA *st;

  assert(db);
  st=LC_HIInsuranceData_new();
  LC_HIInsuranceData_ReadDb(st, db);
  st->_modified=0;
  return st;
}




const char *LC_HIInsuranceData_GetInstitutionId(const LC_HI_INSURANCE_DATA *st) {
  assert(st);
  return st->institutionId;
}


void LC_HIInsuranceData_SetInstitutionId(LC_HI_INSURANCE_DATA *st, const char *d) {
  assert(st);
  if (st->institutionId)
    free(st->institutionId);
  if (d && *d)
    st->institutionId=strdup(d);
  else
    st->institutionId=0;
  st->_modified=1;
}




const char *LC_HIInsuranceData_GetInstitutionName(const LC_HI_INSURANCE_DATA *st) {
  assert(st);
  return st->institutionName;
}


void LC_HIInsuranceData_SetInstitutionName(LC_HI_INSURANCE_DATA *st, const char *d) {
  assert(st);
  if (st->institutionName)
    free(st->institutionName);
  if (d && *d)
    st->institutionName=strdup(d);
  else
    st->institutionName=0;
  st->_modified=1;
}




const GWEN_TIME *LC_HIInsuranceData_GetCoverBegin(const LC_HI_INSURANCE_DATA *st) {
  assert(st);
  return st->coverBegin;
}


void LC_HIInsuranceData_SetCoverBegin(LC_HI_INSURANCE_DATA *st, const GWEN_TIME *d) {
  assert(st);
  if (st->coverBegin)
    GWEN_Time_free(st->coverBegin);
  if (d)
    st->coverBegin=GWEN_Time_dup(d);
  else
    st->coverBegin=0;
  st->_modified=1;
}




const GWEN_TIME *LC_HIInsuranceData_GetCoverEnd(const LC_HI_INSURANCE_DATA *st) {
  assert(st);
  return st->coverEnd;
}


void LC_HIInsuranceData_SetCoverEnd(LC_HI_INSURANCE_DATA *st, const GWEN_TIME *d) {
  assert(st);
  if (st->coverEnd)
    GWEN_Time_free(st->coverEnd);
  if (d)
    st->coverEnd=GWEN_Time_dup(d);
  else
    st->coverEnd=0;
  st->_modified=1;
}




const char *LC_HIInsuranceData_GetStatus(const LC_HI_INSURANCE_DATA *st) {
  assert(st);
  return st->status;
}


void LC_HIInsuranceData_SetStatus(LC_HI_INSURANCE_DATA *st, const char *d) {
  assert(st);
  if (st->status)
    free(st->status);
  if (d && *d)
    st->status=strdup(d);
  else
    st->status=0;
  st->_modified=1;
}




const char *LC_HIInsuranceData_GetGroup(const LC_HI_INSURANCE_DATA *st) {
  assert(st);
  return st->group;
}


void LC_HIInsuranceData_SetGroup(LC_HI_INSURANCE_DATA *st, const char *d) {
  assert(st);
  if (st->group)
    free(st->group);
  if (d && *d)
    st->group=strdup(d);
  else
    st->group=0;
  st->_modified=1;
}




int LC_HIInsuranceData_IsModified(const LC_HI_INSURANCE_DATA *st) {
  assert(st);
  return st->_modified;
}


void LC_HIInsuranceData_SetModified(LC_HI_INSURANCE_DATA *st, int i) {
  assert(st);
  st->_modified=i;
}


void LC_HIInsuranceData_Attach(LC_HI_INSURANCE_DATA *st) {
  assert(st);
  st->_usage++;
}
LC_HI_INSURANCE_DATA *LC_HIInsuranceData_List2__freeAll_cb(LC_HI_INSURANCE_DATA *st, void *user_data) {
  LC_HIInsuranceData_free(st);
return 0;
}


void LC_HIInsuranceData_List2_freeAll(LC_HI_INSURANCE_DATA_LIST2 *stl) {
  if (stl) {
    LC_HIInsuranceData_List2_ForEach(stl, LC_HIInsuranceData_List2__freeAll_cb, 0);
    LC_HIInsuranceData_List2_free(stl); 
  }
}


LC_HI_INSURANCE_DATA_LIST *LC_HIInsuranceData_List_dup(const LC_HI_INSURANCE_DATA_LIST *stl) {
  if (stl) {
    LC_HI_INSURANCE_DATA_LIST *nl;
    LC_HI_INSURANCE_DATA *e;

    nl=LC_HIInsuranceData_List_new();
    e=LC_HIInsuranceData_List_First(stl);
    while(e) {
      LC_HI_INSURANCE_DATA *ne;

      ne=LC_HIInsuranceData_dup(e);
      assert(ne);
      LC_HIInsuranceData_List_Add(ne, nl);
      e=LC_HIInsuranceData_List_Next(e);
    } /* while (e) */
    return nl;
  }
  else
    return 0;
}




