/* This file is auto-generated from "hiinsurancedata.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef HIINSURANCEDATA_P_H
#define HIINSURANCEDATA_P_H

#include "hiinsurancedata_l.h"


struct LC_HI_INSURANCE_DATA {
  GWEN_LIST_ELEMENT(LC_HI_INSURANCE_DATA)
  int _usage;
  int _modified;

  char *institutionId;
  char *institutionName;
  GWEN_TIME *coverBegin;
  GWEN_TIME *coverEnd;
  char *status;
  char *group;
};









#endif /* HIINSURANCEDATA_P_H */
