/* This file is auto-generated from "hipersonaldata.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef HIPERSONALDATA_P_H
#define HIPERSONALDATA_P_H

#include "hipersonaldata_l.h"


struct LC_HI_PERSONAL_DATA {
  GWEN_LIST_ELEMENT(LC_HI_PERSONAL_DATA)
  int _usage;
  int _modified;

  char *insuranceId;
  char *prename;
  char *name;
  char *title;
  char *nameSuffix;
  LC_HI_PERSONAL_DATA_SEX sex;
  GWEN_TIME *dateOfBirth;
  char *addrZipCode;
  char *addrCity;
  char *addrState;
  char *addrCountry;
  char *addrStreet;
  char *addrHouseNum;
};

















#endif /* HIPERSONALDATA_P_H */
