/* This file is auto-generated from "hipersonaldata.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef HIPERSONALDATA_L_H
#define HIPERSONALDATA_L_H

/** @page P_LC_HI_PERSONAL_DATA_LIB LC_HIPersonalData (lib)
This page describes the properties of LC_HI_PERSONAL_DATA
*/
#include <gwenhywfar/misc.h>
#include <gwenhywfar/list2.h>
#include "hipersonaldata.h"
#include <gwenhywfar/misc.h>

#ifdef __cplusplus
extern "C" {
#endif


GWEN_LIST_FUNCTION_DEFS(LC_HI_PERSONAL_DATA, LC_HIPersonalData)
LC_HI_PERSONAL_DATA_LIST *LC_HIPersonalData_List_dup(const LC_HI_PERSONAL_DATA_LIST *stl);

GWEN_LIST2_FUNCTION_DEFS(LC_HI_PERSONAL_DATA, LC_HIPersonalData)

void LC_HIPersonalData_List2_freeAll(LC_HI_PERSONAL_DATA_LIST2 *stl);

















#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* HIPERSONALDATA_L_H */
