/* This file is auto-generated from "starcos_keydescr.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef STARCOS_KEYDESCR_P_H
#define STARCOS_KEYDESCR_P_H

#include "starcos_keydescr_l.h"


struct LC_STARCOS_KEYDESCR {
  GWEN_LIST_ELEMENT(LC_STARCOS_KEYDESCR)
  int _usage;
  int _modified;

  int keyId;
  int status;
  int keyType;
  int keyNum;
  int keyVer;
};








#endif /* STARCOS_KEYDESCR_P_H */
