/* This file is auto-generated from "starcos_keydescr.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "starcos_keydescr_p.h"
#include <gwenhywfar/misc.h>
#include <gwenhywfar/db.h>
#include <gwenhywfar/debug.h>
#include <assert.h>
#include <stdlib.h>
#include <strings.h>

#include <chipcard/cards/starcos.h>
#include <chipcard/chipcard.h>


GWEN_LIST_FUNCTIONS(LC_STARCOS_KEYDESCR, LC_Starcos_KeyDescr)
GWEN_LIST2_FUNCTIONS(LC_STARCOS_KEYDESCR, LC_Starcos_KeyDescr)




LC_STARCOS_KEYDESCR *LC_Starcos_KeyDescr_new() {
  LC_STARCOS_KEYDESCR *st;

  GWEN_NEW_OBJECT(LC_STARCOS_KEYDESCR, st)
  st->_usage=1;
  GWEN_LIST_INIT(LC_STARCOS_KEYDESCR, st)
  return st;
}


void LC_Starcos_KeyDescr_free(LC_STARCOS_KEYDESCR *st) {
  if (st) {
    assert(st->_usage);
    if (--(st->_usage)==0) {
  GWEN_LIST_FINI(LC_STARCOS_KEYDESCR, st)
  GWEN_FREE_OBJECT(st);
    }
  }

}


LC_STARCOS_KEYDESCR *LC_Starcos_KeyDescr_dup(const LC_STARCOS_KEYDESCR *d) {
  LC_STARCOS_KEYDESCR *st;

  assert(d);
  st=LC_Starcos_KeyDescr_new();
  st->keyId=d->keyId;
  st->status=d->status;
  st->keyType=d->keyType;
  st->keyNum=d->keyNum;
  st->keyVer=d->keyVer;
  return st;
}


int LC_Starcos_KeyDescr_toDb(const LC_STARCOS_KEYDESCR *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "keyId", st->keyId))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "status", st->status))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "keyType", st->keyType))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "keyNum", st->keyNum))
    return -1;
  if (GWEN_DB_SetIntValue(db, GWEN_DB_FLAGS_OVERWRITE_VARS, "keyVer", st->keyVer))
    return -1;
  return 0;
}


int LC_Starcos_KeyDescr_ReadDb(LC_STARCOS_KEYDESCR *st, GWEN_DB_NODE *db) {
  assert(st);
  assert(db);
  LC_Starcos_KeyDescr_SetKeyId(st, GWEN_DB_GetIntValue(db, "keyId", 0, 0));
  LC_Starcos_KeyDescr_SetStatus(st, GWEN_DB_GetIntValue(db, "status", 0, 0));
  LC_Starcos_KeyDescr_SetKeyType(st, GWEN_DB_GetIntValue(db, "keyType", 0, 0));
  LC_Starcos_KeyDescr_SetKeyNum(st, GWEN_DB_GetIntValue(db, "keyNum", 0, 0));
  LC_Starcos_KeyDescr_SetKeyVer(st, GWEN_DB_GetIntValue(db, "keyVer", 0, 0));
  return 0;
}


LC_STARCOS_KEYDESCR *LC_Starcos_KeyDescr_fromDb(GWEN_DB_NODE *db) {
  LC_STARCOS_KEYDESCR *st;

  assert(db);
  st=LC_Starcos_KeyDescr_new();
  LC_Starcos_KeyDescr_ReadDb(st, db);
  st->_modified=0;
  return st;
}




int LC_Starcos_KeyDescr_GetKeyId(const LC_STARCOS_KEYDESCR *st) {
  assert(st);
  return st->keyId;
}


void LC_Starcos_KeyDescr_SetKeyId(LC_STARCOS_KEYDESCR *st, int d) {
  assert(st);
  st->keyId=d;
  st->_modified=1;
}




int LC_Starcos_KeyDescr_GetStatus(const LC_STARCOS_KEYDESCR *st) {
  assert(st);
  return st->status;
}


void LC_Starcos_KeyDescr_SetStatus(LC_STARCOS_KEYDESCR *st, int d) {
  assert(st);
  st->status=d;
  st->_modified=1;
}




int LC_Starcos_KeyDescr_GetKeyType(const LC_STARCOS_KEYDESCR *st) {
  assert(st);
  return st->keyType;
}


void LC_Starcos_KeyDescr_SetKeyType(LC_STARCOS_KEYDESCR *st, int d) {
  assert(st);
  st->keyType=d;
  st->_modified=1;
}




int LC_Starcos_KeyDescr_GetKeyNum(const LC_STARCOS_KEYDESCR *st) {
  assert(st);
  return st->keyNum;
}


void LC_Starcos_KeyDescr_SetKeyNum(LC_STARCOS_KEYDESCR *st, int d) {
  assert(st);
  st->keyNum=d;
  st->_modified=1;
}




int LC_Starcos_KeyDescr_GetKeyVer(const LC_STARCOS_KEYDESCR *st) {
  assert(st);
  return st->keyVer;
}


void LC_Starcos_KeyDescr_SetKeyVer(LC_STARCOS_KEYDESCR *st, int d) {
  assert(st);
  st->keyVer=d;
  st->_modified=1;
}




int LC_Starcos_KeyDescr_IsModified(const LC_STARCOS_KEYDESCR *st) {
  assert(st);
  return st->_modified;
}


void LC_Starcos_KeyDescr_SetModified(LC_STARCOS_KEYDESCR *st, int i) {
  assert(st);
  st->_modified=i;
}


void LC_Starcos_KeyDescr_Attach(LC_STARCOS_KEYDESCR *st) {
  assert(st);
  st->_usage++;
}
LC_STARCOS_KEYDESCR *LC_Starcos_KeyDescr_List2__freeAll_cb(LC_STARCOS_KEYDESCR *st, void *user_data) {
  LC_Starcos_KeyDescr_free(st);
return 0;
}


void LC_Starcos_KeyDescr_List2_freeAll(LC_STARCOS_KEYDESCR_LIST2 *stl) {
  if (stl) {
    LC_Starcos_KeyDescr_List2_ForEach(stl, LC_Starcos_KeyDescr_List2__freeAll_cb, 0);
    LC_Starcos_KeyDescr_List2_free(stl); 
  }
}


LC_STARCOS_KEYDESCR_LIST *LC_Starcos_KeyDescr_List_dup(const LC_STARCOS_KEYDESCR_LIST *stl) {
  if (stl) {
    LC_STARCOS_KEYDESCR_LIST *nl;
    LC_STARCOS_KEYDESCR *e;

    nl=LC_Starcos_KeyDescr_List_new();
    e=LC_Starcos_KeyDescr_List_First(stl);
    while(e) {
      LC_STARCOS_KEYDESCR *ne;

      ne=LC_Starcos_KeyDescr_dup(e);
      assert(ne);
      LC_Starcos_KeyDescr_List_Add(ne, nl);
      e=LC_Starcos_KeyDescr_List_Next(e);
    } /* while (e) */
    return nl;
  }
  else
    return 0;
}




