/* This file is auto-generated from "starcos_keydescr.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef STARCOS_KEYDESCR_L_H
#define STARCOS_KEYDESCR_L_H

/** @page P_LC_STARCOS_KEYDESCR_LIB LC_Starcos_KeyDescr (lib)
This page describes the properties of LC_STARCOS_KEYDESCR
*/
#include <gwenhywfar/misc.h>
#include <gwenhywfar/list2.h>
#include "starcos_keydescr.h"
#include <gwenhywfar/misc.h>

#ifdef __cplusplus
extern "C" {
#endif


GWEN_LIST_FUNCTION_DEFS(LC_STARCOS_KEYDESCR, LC_Starcos_KeyDescr)
LC_STARCOS_KEYDESCR_LIST *LC_Starcos_KeyDescr_List_dup(const LC_STARCOS_KEYDESCR_LIST *stl);

GWEN_LIST2_FUNCTION_DEFS(LC_STARCOS_KEYDESCR, LC_Starcos_KeyDescr)

void LC_Starcos_KeyDescr_List2_freeAll(LC_STARCOS_KEYDESCR_LIST2 *stl);








#ifdef __cplusplus
} /* __cplusplus */
#endif


#endif /* STARCOS_KEYDESCR_L_H */
