/* This file is auto-generated from "pininfo.xml" by the typemaker
   tool of Gwenhywfar. 
   Do not edit this file -- all changes will be lost! */
#ifndef PININFO_P_H
#define PININFO_P_H

#include "pininfo_l.h"


struct LC_PININFO {
  GWEN_INHERIT_ELEMENT(LC_PININFO)
  GWEN_LIST_ELEMENT(LC_PININFO)
  int _usage;
  int _modified;

  char *name;
  uint32_t id;
  int encoding;
  int minLength;
  int maxLength;
  int allowChange;
  int filler;
};










#endif /* PININFO_P_H */
